name: whatsapp
description: "Whatsapp Clone"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #cloud_firestore: ^4.14.0
  #concentric_transition: ^1.0.3
  #firebase_auth: ^4.16.0
  #firebase_core: ^2.24.2
  #firebase_storage: ^11.6.0
  #firebase_ui_firestore: ^1.6.1
  #flutter_animate: ^4.4.0
  #get: ^4.6.6
  #hand_signature: ^3.0.2
  #hive: ^2.2.3
  icons_plus: ^5.0.0
  date_format: ^2.0.7
  #lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
    - assets/images/
    - assets/jsons/
    - assets/svgs/
