name: whatsapp
description: "Whatsapp Clone"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_ui_firestore: ^1.6.1
  flutter_animate: ^4.4.0
  get: ^4.6.6
  hive: ^2.2.3
  icons_plus: ^5.0.0
  date_format: ^2.0.7
  lottie: ^3.0.0
  cached_network_image: ^3.3.1
  chat_bubbles: ^1.5.0
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  mime: ^1.0.4
  open_filex: ^4.3.4
  path_provider: ^2.1.2
  http: ^1.2.0
  voice_message_package: ^2.1.4
  selectable_autolink_text: ^2.6.0
  flag: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
    - assets/images/
    - assets/jsons/
    - assets/svgs/
